### ISSUE TITLE
Mention that you must build extension before packing it

### ISSUE THREAD

**Issue by veeral-patel** [palantir/phishcatch#23]
I was trying to follow this wiki step:

https://github.com/palantir/phishcatch/wiki/Installing-the-extension#building-and-installing-from-source

> Download the source code from this repo.
> In Chrome, open chrome://extensions/ and enable the "Developer mode" toggle in the top right.
> Click the "Pack extension" button and select the extension folder from your local copy of this repo as the "Extension root directory".

Specifically, here's what I did
1. Cloned the phishcatch repo from GitHub
2. Clicked Pack Extension and selected my `phishcatch/extension` folder locally

However I kept getting a "manifest file not found error"

Through trial and error I learned that the instructions are misleading, and here's what I need to do:
1. Clone the phishcatch repo
2. Go into `extension` and run `yarn install` and `yarn build`
3. Click Pack Extension and choose the resulting `phishcatch/extension/dist` folder

Let's update the wiki page with the up to date instructions no?

I would create a PR but I can't as this is a wiki page!

**Comment by carbureted** [comment]
Great feedback! Is it more clear now?

**Comment by veeral-patel** [comment]
@carbureted thanks! feel free to close.
