### ISSUE TITLE
Document how to configure without centralized management

### ISSUE THREAD

**Issue by veeral-patel** [palantir/phishcatch#24]
So I know you can configure phishcatch using the instructions here

https://github.com/palantir/phishcatch/wiki/Configuring-the-extension#deploying-configuration-settings-via-enterprise-management

However, I am setting up phishcatch on my personal browser on my Mac. I've installed from the Chrome web store. I don't have Jamf Pro and have no intentions to get one for personal use :). Is there any way I can configure phishcatch?

**Comment by carbureted** [comment]
There's a "debug" button at the top of the screen that allows you to make arbitrary config changes. I'd like to add realtime validation to make experimenting with it easier - let me know if you hit any particular snags.

**Comment by carbureted** [comment]
Updated the wiki with these instructions.
