### ISSUE TITLE
FastAPI 0.65.2 Wiki isn't working with phishcatch

### ISSUE THREAD

**Issue by 0xMirasio** [palantir/phishcatch#27]
FastAPI 0.65.2 has changed their methods to parse JSON data. 
The command in wiki (triggering alert, etc...) aren't working, and probably some code in the application. 
(Error: invalid_dict)

A solution is to downgrade to fastAPI 0.65.1 while waiting for a better version. 
Original issue in fastAPI git : 
https://www.gitmemory.com/issue/tiangolo/fastapi/3373/861173889

**Comment by carbureted** [comment]
I think https://github.com/palantir/phishcatch/pull/28 should work
