### ISSUE TITLE
[enhancement] Adding Parameter in config for better Username Detection. 

### ISSUE THREAD

**Issue by 0xMirasio** [palantir/phishcatch#29]
Add a new parameters in debug configuration which taking as input a string : idusername
This string should be the value of the id on the MainPage, to detect the username.

for example, a main login page with the html code : 
`<input class="mdc-text-field__input pwd" type="password" id="pwd_pass" size="25"  name="password" value="">` 

The Parameter isUsername should be pwd_pass, then the extension can automatically take the username when logging and store it for better logging/information. 

New code should have for example in content.js

`function runUsernameScraper() {
  const username = <HTMLInputElement>document.getElementById(IdUsername)
  if (username != null) { 
    return username.value
  }`

**Comment by carbureted** [comment]
👍 
Great feedback. Will add this.
